spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 3000
        max-attempts: 5
        max-interval: 10000
